- name: configure Intel graphics driver
  template:
    dest: /etc/modprobe.d/i915.conf
    mode: 0644
    src: i915/i915.conf.j2
  register: kernel_parameters

- name: disable IOMMU via grub
  lineinfile:
    backrefs: yes
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=off\4"'
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*?)(( intel_iommu=[^\\s]*)(.*?))?\"$"

- name: update initramfs and grub
  shell: update-initramfs -u && update-grub
  when: kernel_parameters.changed

- name: configure reachable BIOS settings
  include_tasks: write_system_file.yml
  loop:
    - path: /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/fn_lock
      content: "1"
    # https://wiki.archlinux.org/title/Laptop/Lenovo#Battery_Conservation_Mode_on_IdeaPad_laptops
    - path: /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode
      content: "1"
    # https://www.reddit.com/r/archlinux/comments/o4tlsk/comment/h2j4c9g/?utm_source=share&utm_medium=web2x&context=3
    - path: /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/fan_mode
      content: "0"
  loop_control:
    loop_var: system_file

- name: install lightdm
  apt:
    cache_valid_time: 600
    name:
      - lightdm
