- name: configure Intel graphics driver
  template:
    dest: /etc/modprobe.d/i915.conf
    mode: 0644
    src: i915/i915.conf.j2
  register: kernel_parameters

- name: disable IOMMU via grub
  lineinfile:
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_iommu=off"
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="

- name: update initramfs and grub
  shell: update-initramfs -u && update-grub
  when: kernel_parameters.changed

- name: install lightdm
  apt:
    cache_valid_time: 600
    name:
      - lightdm