- name: install command line software packages
  apt:
    cache_valid_time: 600
    name:
      - htop
      - iotop
      - terminator

- name: configure shell files
  copy:
    src: "{{ item }}"
    dest: "{{ user.home_dir }}/"
  loop:
    - .bash_aliases
    - .profile
  become: no

- name: configure SSH
  template:
    src: "ssh/config.j2"
    dest: "{{ user.home_dir }}/.ssh/config"
