- name: add Microsoft package source
  template:
    dest: /etc/apt/sources.list.d/vscode.list
    src: vscode/apt/vscode.list.j2
  register: sources_vscode

- name: install Microsoft GPG key and update
  shell: |
    ( wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg ) \
    && install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/ \
    && rm packages.microsoft.gpg \
    && apt update
  when: sources_vscode.changed

- name: install development software packages
  apt:
    cache_valid_time: 600
    name:
      - code
      - git
      - filezilla
      - make

- name: template configuration files
  template:
    dest: "{{ item.dest | default( default_item_dest ) }}"
    mode: "{{ item.mode }}"
    src: "{{ item.name }}.j2"
  loop:
    - name: git/.gitconfig
      dest_dir: "{{ git_config_dir }}"
      mode: "{{ git_config_mode }}"
    - name: vscode/settings.json
      dest_dir: "{{ vscode_user_config_dir }}"
      mode: "{{ vscode_user_config_mode }}"
    - name: vscode/keybindings.json
      dest_dir: "{{ vscode_user_config_dir }}"
      mode: "{{ vscode_user_config_mode }}"
  vars:
    default_item_dest: "{{ item.dest_dir | default( user.home_dir ) }}/{{ item.name | basename }}"
  become: no
