- name: register SlimbookBattery PPA
  apt_repository:
    repo: ppa:slimbook/slimbook

- name: install power and heat management software packages
  apt:
    cache_valid_time: 600
    name:
      - powertop
      - slimbookbattery
      - thermald
      - tlp

# https://www.reddit.com/r/archlinux/comments/3okrhl/comment/cvy35q6/?utm_source=share&utm_medium=web2x&context=3
# TODO unclear whether required
- name: enable services
  service:
    enabled: yes
    name: thermald

# https://askubuntu.com/a/1261531
- name: configure battery notifications
  blockinfile:
    block: |
      PercentageLow=30
      PercentageCritical=15
    marker: "# {mark} PERSONAL NOTEBOOK SETUP (ANSIBLE) - BATTERY NOTIFICATIONS"
    path: /etc/UPower/UPower.conf
  register: upower_config

- name: enable battery notifications
  service:
    name: upower
    state: restarted
  when: upower_config.changed

- name: enable suspend with external monitor
  dconf:
    key: /org/gnome/settings-daemon/plugins/power/lid-close-suspend-with-external-monitor
    value: "true"
  become: no

- name: configure UPower for proper suspension
  blockinfile:
    block: |
      # disable broken lid state detection
      IgnoreLid=true
    marker: "# {mark} PERSONAL NOTEBOOK SETUP (ANSIBLE) - CONFIGURE SUSPEND"
    path: /etc/UPower/UPower.conf
