- name: register SlimbookBattery PPA
  apt_repository:
    repo: ppa:slimbook/slimbook

- name: install power and heat management software packages
  apt:
    cache_valid_time: 600
    name:
      - powertop
      - slimbookbattery
      - thermald
      - tlp

# https://www.reddit.com/r/archlinux/comments/3okrhl/comment/cvy35q6/?utm_source=share&utm_medium=web2x&context=3
# TODO unclear whether required
- name: enable services
  service:
    enabled: yes
    name: thermald

# https://askubuntu.com/a/1261531
- name: configure battery notifications
  blockinfile:
    block: |
      PercentageLow=30
      PercentageCritical=15
    marker: "# {mark} PERSONAL NOTEBOOK SETUP (ANSIBLE) - BATTERY NOTIFICATIONS"
    path: /etc/UPower/UPower.conf
  register: upower_config

- name: enable battery notifications
  service:
    name: upower
    state: restarted
  when: upower_config.changed

# https://apiraino.github.io/ubuntu-gnome-power/
- name: configure GNOME power settings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - description: dim screen
      key: idle-dim
      value: 'true'
    - description: enable suspend with external monitor
      key: lid-close-suspend-with-external-monitor
      value: 'true'
    - description: enable automatic suspend on battery
      key: sleep-inactive-battery-type
      value: "'suspend'"
    - description: automatic suspend on battery after 30 min
      key: sleep-inactive-battery-timeout
      value: 1800
    - description: disable automatic suspend on AC
      key: sleep-inactive-ac-type
      value: "'nothing'"
  loop_control:
    label: "{{ item.description }}"
  become: no

- name: configure UPower for proper suspension
  blockinfile:
    block: |
      # disable broken lid state detection
      IgnoreLid=true
    marker: "# {mark} PERSONAL NOTEBOOK SETUP (ANSIBLE) - CONFIGURE SUSPEND"
    path: /etc/UPower/UPower.conf

- name: setup hibernation support
  import_tasks: hibernate.yml
